import Head from 'next/head'
import Link from 'next/link'

import styles from '../../styles/MovieItem.module.css'

export async function getServerSideProps(context) {

    const response = await fetch(`http://localhost:3000/api/movie/${context.params.id}`)
    const json = await response.json()

    return {
        props: {
            info: json.info
        }
    }
}

export default function MovieItem({ info }) {
  
  const data = new Date(info.release_date)
  
  const setVoteColor = (vote) => {
    if (vote >= 8) {
      return "green"
    } else if (vote >= 6){
      return "orange"
    } else {
      return "red"
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.movie_container}>
          <Link href="/">
            <strong>Voltar</strong>
          </Link>
          <h1 className={styles.title}>
            {info.title} 
          </h1>
          <span style={{color: `${setVoteColor(info.vote_average)}`}}>{info.vote_average}</span> <span>{data.getFullYear()}</span>
          <p>{info.overview}</p>
        </div>
        <img className={styles.img_backdrop} src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="400"/>
      </main>
    </div>
  )
}